flags: {}

packages:
- .
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 77b2a505bcd5aba0b55b7ed09107dc779a3aced6
  extra-dep: true

resolver: lts-5.3

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20160414_ghc-7.10.3:
     url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
     sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

extra-deps:
  - ref-tf-0.4
  - these-0.6.2.1
  - ghcjs-dom-0.2.3.1
  - reflex-dom-0.3
  - clay-0.11
