#!/usr/bin/env bash
set -e

cd src/WebGui/
if [ ! -d "reflex-dom" ]; then
    git clone -b develop https://github.com/ryantrinkle/reflex-dom.git
    git reset --hard 4ce94d0afe35f5642e985800dd89fa457b324a07
fi
sed -i.bak -e "s/bifunctors == 4\.2\.\*/bifunctors >= 4\.2/g" reflex-dom/reflex-dom.cabal

stack build

# I have two projects, the executable cannot find the html/js
# generated by the cigale-web project. Copy the files so they'll
# be found.
htmljspath=$(stack path --local-install-root)
cd ../..
stack install
exepath=$(stack path --local-install-root)
cp -R "$htmljspath/bin/cigale-web.jsexe" "$exepath/share"

find lib/ -name "*.css" -exec cp \{\} "$exepath/share/cigale-web.jsexe/" \;
cp -R lib/glyphicons_free/ "$exepath/share/cigale-web.jsexe/"
