#!/usr/bin/env bash
set -e

if [ ! -e "lib/.v4" ]; then
    rm -Rf lib/node_modules/
    mkdir -p lib/node_modules
    npm install pikaday@1.7.0 --prefix lib
    npm install jquery@3.1.1 --prefix lib
    npm install popper.js@1.14.3 --prefix lib
    npm install bootstrap@4.1.0 --prefix lib
    npm install emoji-datasource@3.0.0 --prefix lib
    npm install node@8.9.4 --prefix lib # ghcjs#668
    touch lib/.v4
fi
export PATH=./lib/node_modules/node/bin/:$PATH

# i need slack 1.x for the ghcjs support, 'stack setup'
# ghcjs support was dropped for slack 2.x...
if [ ! -e "stack" ]; then
    mkdir stack
    cd stack
    wget https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz
    tar xvfz stack-1.9.3-linux-x86_64.tar.gz
    cd ..
fi

cd src/WebGui/

# install the ghcjs compiler
echo "will now install the GHCJS compiler, this should take a while..."
../../stack/stack-1.9.3-linux-x86_64/stack setup
echo "installed the GHCJS compiler!"

# happy needs GHC in the path to build.
# add the GHC we just set up to the path.
cd ../..
export PATH=$PATH:`stack path --bin-path`
cd src/WebGui/

echo "building the client-side app"
../../stack/stack-1.9.3-linux-x86_64/stack build
echo "built the client-side app"

# I have two projects, the executable cannot find the html/js
# generated by the cigale-web project. Copy the files so they'll
# be found.
htmljspath=$(stack path --local-install-root)
cd ../..

# install the ghc compiler
echo "will now install the ghc compiler, this may take a while..."
stack setup
echo "installed the GHC compiler!"

stack install
exepath=$(stack path --local-install-root)
mkdir -p "$exepath"

cp -R "$htmljspath/bin/cigale-web.jsexe" "$exepath/share"

# pikaday has a strange .c9 folders with a bad pikaday.css.
find lib/ -name "*.css" -not -path "*/.c9/*" -exec cp \{\} "$exepath/share/cigale-web.jsexe/" \;
cp -R lib/glyphicons_free/ "$exepath/share/cigale-web.jsexe/"
cp -R lib/node_modules/emoji-datasource "$exepath/share/cigale-web.jsexe/"

echo "built the app, copied the files, all set up and ready to go!"
