#!/usr/bin/env bash
set -e

if [ ! -e "lib/.v2" ]; then
    rm -Rf lib/node_modules/
    mkdir -p lib/node_modules
    npm install pikaday@1.6.1 --prefix lib
    npm install jquery@3.1.1 --prefix lib
    npm install popper.js@1.11.1 --prefix lib
    npm install bootstrap@4.0.0-beta --prefix lib
    npm install emoji-datasource@3.0.0 --prefix lib
    touch lib/.v2
fi

cd src/WebGui/

# install the ghcjs compiler
echo "will now install the GHCJS compiler, this should take a while..."
stack setup
echo "installed the GHCJS compiler!"

# happy needs GHC in the path to build.
# add the GHC we just set up to the path.
cd ../..
export PATH=$PATH:`stack path --bin-path`
cd src/WebGui/

stack install happy
export PATH=$PATH:~/.local/bin

echo "building the client-side app"
stack build
echo "built the client-side app"

# I have two projects, the executable cannot find the html/js
# generated by the cigale-web project. Copy the files so they'll
# be found.
htmljspath=$(stack path --local-install-root)
cd ../..

# install the ghc compiler
echo "will now install the ghc compiler, this may take a while..."
stack setup
echo "installed the GHC compiler!"

stack install
exepath=$(stack path --local-install-root)

cp -R "$htmljspath/bin/cigale-web.jsexe" "$exepath/share"

# pikaday has a strange .c9 folders with a bad pikaday.css.
find lib/ -name "*.css" -not -path "*/.c9/*" -exec cp \{\} "$exepath/share/cigale-web.jsexe/" \;
cp -R lib/glyphicons_free/ "$exepath/share/cigale-web.jsexe/"
cp -R lib/node_modules/emoji-datasource "$exepath/share/cigale-web.jsexe/"

echo "built the app, copied the files, all set up and ready to go!"
